# Use the official Node.js image from the Docker Hub
FROM node:alpine

# Create and set the working directory
WORKDIR ./


# Copy package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the API Gateway will run on
EXPOSE 8000


# Define the command to run the API Gateway
CMD [ "node", "index.js" ]
